# Generated by Django 5.1 on 2024-09-05 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_added_date_alter_todo_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='iscompleted',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='prior',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AlterField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 3, 33, 46, 772507)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='taskname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
