# Generated by Django 5.1 on 2024-09-05 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_todo_deadline_remove_todo_iscompleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 3, 36, 38, 423865)),
        ),
    ]
