# Generated by Django 5.1 on 2024-09-09 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_todo_added_date_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 23, 36, 45, 888080)),
        ),
    ]
